# We have a conf and classes directory, add to BBPATH
BBPATH .= ":${LAYERDIR}"

# We have recipes-* directories, add to BBFILES
BBFILES += "${LAYERDIR}/recipes-*/*/*.bb \
            ${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "meta-aibaos"
BBFILE_PATTERN_meta-aibaos = "^${LAYERDIR}/"
BBFILE_PRIORITY_meta-aibaos = "6"

LAYERDEPENDS_meta-aibaos = "core"
LAYERSERIES_COMPAT_meta-aibaos = "scarthgap"
