DISTRO_NAME = "iBaOS"
DISTRO_VERSION = "0.0.1"
DISTRO_CODENAME = "core-alpha"
SDK_VENDOR = "-aibaos"
MAINTAINER = "AIBAOS Team <team@aibaos.org>"

INIT_MANAGER = "systemd"
VIRTUAL-RUNTIME_init_manager = "systemd"
VIRTUAL-RUNTIME_initscripts = "systemd-compat-units"
DISTRO_FEATURES:append = " systemd"
DISTRO_FEATURES_BACKFILL_CONSIDERED:append = " sysvinit"